version: "3.8"

services:
    db:
        image: postgis/postgis:latest
        environment:
            POSTGRES_DB: pollution-data
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - data:/usr/src/app/data
        ports:
            - "5432:5432"

    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DB_NAME=pollution-data
            - DB_USER=admin
            - DB_PASSWORD=admin
            - DB_HOST=db
            - DB_PORT=5432
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_EMAIL=admin@example.com
            - DJANGO_SUPERUSER_PASSWORD=django123

volumes:
    postgres_data:
    data:
