# Generated by Django 5.1.2 on 2024-12-04 11:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('total_number_measurements', models.IntegerField(default=0)),
                ('last_standard', models.CharField(max_length=50, null=True)),
                ('last_measurement_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AQIStandard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lower_limit', models.FloatField(null=True)),
                ('upper_limit', models.FloatField(null=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AQIMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pollution', models.FloatField()),
                ('noise', models.FloatField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.aqipoint')),
                ('standard', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aqistandard')),
            ],
        ),
    ]
